### ISSUE TITLE
Update Register.html to new format

### ISSUE THREAD

**Issue by JamesShadowfyre** [Birdbh/Engicoders#103]
Register.html is currently unappealing visually. It must be updated to enhance user experience. 
The boxes within the form should be aligned, and the text font and size should be consistent.

**Comment by Reebs296** [comment]
Could you explain what you mean by new format? I am working on updating the style.css, in another issue so let me know if there's a standard you want it to follow?

**Comment by JamesShadowfyre** [comment]
That's exactly what is needed. 
I assume this is one of the many duplicate issues we have. 
Style CSS, apply it to the register page, make sure textboxes and stuff line up. 
Thanks!

**Comment by JamesShadowfyre** [comment]
Finished by @Reebs296 on #201
