### ISSUE TITLE
Fix Database tests in test_db

### ISSUE THREAD

**Issue by Jcp149** [Birdbh/Engicoders#114]
I ran into errors while trying to make the test_db file, this is a mix of code and computer issues

**Comment by Jcp149** [comment]
after much issues, my vscode recognizes sqlite, flask, and other imports. this came down to selecting the correct file

**Comment by Jcp149** [comment]
my vscode testing now doesnt work, it allows me to test for about 5 minutes and then wont load new tests, when i try to reset my vscode it doesnt "find" any tests in the code with pytest

**Comment by Jcp149** [comment]
i added some code to conftest to hopefully make the runner and app functions work in the db test, but im not sure since my testing stuff isnt working

**Comment by JamesShadowfyre** [comment]
![image](https://github.com/Birdbh/Engicoders/assets/88523672/07fcdb5b-d8eb-4a64-afa5-f9e4d113056b)
![image](https://github.com/Birdbh/Engicoders/assets/88523672/76975ffc-8929-4a4f-b4e4-7f7ce20e2cc4)
![image](https://github.com/Birdbh/Engicoders/assets/88523672/849a4deb-50b9-4abb-be0e-bcdbd42b590f)
Run these commands ahead of tests

**Comment by JamesShadowfyre** [comment]
![image](https://github.com/Birdbh/Engicoders/assets/88523672/64a3f93e-7754-4df2-bf89-71131ef3315d)
This needed to be added to init.py

**Comment by JamesShadowfyre** [comment]
General Reminder: if calling on a function remember the brackets 
![image](https://github.com/Birdbh/Engicoders/assets/88523672/fc0c022d-d8f7-457e-80de-523c611c9877)
