### ISSUE TITLE
Develop home.py to get field data in the home.html fields and request data from DataGeneration Object, Cleanse Data, and Pass Data for visulization

### ISSUE THREAD

**Issue by Birdbh** [Birdbh/Engicoders#132]
How to send graph data to HTML page: https://www.youtube.com/watch?v=E2hytuQvLlE

This should be created as a blueprint: https://flask.palletsprojects.com/en/3.0.x/blueprints/

This should include a POST request (if request.method == 'POST') to get data on the forms, and call the DataGeneration object to get data. Create a sensor object from that data. Send the sensor values to the "labels" and "values" variables.

In the future will require setting a threshold for alarms, (May not be implemented in home.html by the end of the week)

For the blueprint, it needs the re-direct address of the home (@bp.route('/home', methods=('GET', 'POST'))

**Comment by Jcp149** [comment]
Requires: https://github.com/Birdbh/Engicoders/issues/99

Create the backend form data for the home.py. This will include the ability to choose upload data, select data stream, or choose to process and analyze data.

Create this by March 22.

-james' older version of this issue
