### ISSUE TITLE
Fix M2

### ISSUE THREAD

**Issue by Jcp149** [Birdbh/Engicoders#208]
Go through the M2 document and apply all of the inputs that rohit left on it and add it to the deliverable folder. main issues are with the case diagram and some things need more explaining. ALSO update it to match what the current outlook of the project is, it has changed a little bit!

**Comment by JamesShadowfyre** [comment]
By making these changes will it improve our M2 mark?

**Comment by JamesShadowfyre** [comment]
@Jcp149 Is this done and ready to be reviewed?
