### ISSUE TITLE
Adjust label definition of charting functionality so that Datetime objects integrate with Chart.js

### ISSUE THREAD

**Issue by Birdbh** [Birdbh/Engicoders#214]
Right now there is an issue with passing our labels as strings, this leads to charting formatting ugliess. This should be adjusted.

**Comment by Jcp149** [comment]
after trying to find and attempt solutions online and on youtube to allow chart.js to intake a datetime object (reddit, youtube, and stackoverflow was useless), i searched on chart.js website itself, and it seems like they're take on dates and times is to, by hand, put in the values as seen in the picture below. so what we have at the moment with taking a date time object from the sensor, passing it through the chart class to get the string version of the date time object is exactly what chart.js wants us to do!

(this is from the chart.js website where it has all the options for the charts. its deep within the axes and cartesian section.)

![Image](https://github.com/Birdbh/Engicoders/assets/156832550/57c5f28f-5ba6-4684-ad81-676bc2f9fde4)
