### ISSUE TITLE
Alter the charts to allow for 2 extra lines for the alarms

### ISSUE THREAD

**Issue by Jcp149** [Birdbh/Engicoders#231]
add 2 extra dataset entries to the chart code on the html to allow input for 2 more "datasets" of a straight high and low alarm. if no alarm is input, these lines should stay blank.

**Comment by Jcp149** [comment]
i was unable to do this this week since alex's pr wasnt approved with the implementation of the alarm stuff in the front end and burke could not figure out the chart stuff in the back end. but, i have a good idea of how to start this and hopefully get it fully working. 

in the pic below i would add 2 more sections of inputs passed into the home page of the high and low limits which would be repeated over the length of the sensor and displayed in the chart in separate datasets. and if alarms arent selected, since they dont have to be, the data would be null and not show up.

![Image](https://github.com/Birdbh/Engicoders/assets/156832550/f65b9997-1b2b-4d52-8997-1b811ede3fa6)

**Comment by JamesShadowfyre** [comment]
Complete with the alarms PR #247
