### ISSUE TITLE
User Story: Download Visualizations

### ISSUE THREAD

**Issue by Birdbh** [Birdbh/Engicoders#38]
As a regular user, I want to be able to download the visualizations that I have made so that I can save it for future use.
_Acceptance Criteria: Once visualized, there will be a button to download the visualization and alarm log to the local device which, when clicked, will bring up a screen to select the save location._

**Comment by JamesShadowfyre** [comment]
https://quickchart.io/documentation/chart-js/image-export/ 
Notes so I can do this later

**Comment by JamesShadowfyre** [comment]
Complete with #252
