### ISSUE TITLE
Log in Page System

### ISSUE THREAD

**Issue by JamesShadowfyre** [Birdbh/Engicoders#51]
This is here to document the progress of the login page. 
The goal of this issue is to implement the login page for a user. The login page will allow the user to enter their account credentials and gain access to the system.

**Comment by JamesShadowfyre** [comment]
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-v-user-logins 
This tutorial is acting as a guide for login

**Comment by Reebs296** [comment]
The HTML page has been made. The HTML code can be found under the static folder called "loginPage.html", it is linked with the file loginPage.py. Please add any comments or suggestions to this layout. Thanks.

**Comment by JamesShadowfyre** [comment]
Complete with #194
